### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by VsyachePuz** [vit1251/xlexview#1]
And short license name (like 'unlicense' or 'BSD'). This is necessary for packaging in various distributions. 

Application icon (.png 64x64 will be also usefull)

**Comment by vit1251** [comment]
Hello @VsyachePuz,

I thought that it is possible to deliver the product on MIT license, and also took a picture made in 2004 between lessons at the faculty of computer scince in my usniversity for Widndows version of this program.

I keep historical versions but all of them are certainly outdated. And if you would wonder, then this program materials located on the site www.lexview.ru

I am glad that this program is useful to you.
